/*
Navicat MySQL Data Transfer

Source Server         : 101.251.99.194
Source Server Version : 50717
Source Host           : 101.251.99.194:33306
Source Database       : fenxiao

Target Server Type    : MYSQL
Target Server Version : 50717
File Encoding         : 65001

Date: 2018-07-03 17:12:57
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for fx_advert
-- ----------------------------
DROP TABLE IF EXISTS `fx_advert`;
CREATE TABLE `fx_advert` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `adname` varchar(60) NOT NULL COMMENT '广告名称',
  PRIMARY KEY (`id`,`adname`),
  UNIQUE KEY `name` (`adname`)
) ENGINE=InnoDB AUTO_INCREMENT=2072 DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Records of fx_advert
-- ----------------------------
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('58', 'b612咔叽');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1888', 'b612咔叽-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1863', 'b612咔叽-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2018', 'b612咔叽-QForJXX');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1946', 'Hello语音交友');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('81', 'kk直播');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('13', 'qq飞车');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1887', 'qq飞车-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1969', 'Tiki');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2008', 'UC浏览器');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2035', 'UC浏览器-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2007', 'UC浏览器-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2003', 'UU跑腿');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1965', '一点资讯');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1927', '一点资讯-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('42', '一直播');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1968', '万象物语');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1867', '万象物语-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1881', '万象物语-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1842', '三国杀名将传');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2059', '三国杀名将传-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1926', '三国杀名将传-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1931', '三国杀名将传-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2030', '不朽凡人');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1944', '中土纪元');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('31', '九州行');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2050', '乱世王者');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2023', '云裳羽衣');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1828', '京东到家');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1843', '京东商城');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2040', '京东商城-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1865', '京东商城-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1869', '京东商城-W');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1870', '京东商城-WW');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1972', '京东商城-WWW');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('49', '京东金融');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2027', '京东金融-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1977', '人人贷借款');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('36', '仙剑云之凡');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1901', '仙剑云之凡-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('54', '仙路奇缘');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1906', '仙路奇缘-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1903', '仙路奇缘-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1985', '优酷');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1995', '优酷-0');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2021', '优酷-W');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1885', '传奇世界-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1890', '传奇世界-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2033', '侠客风云传');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1955', '倩女幽魂');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2056', '倩女幽魂-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1878', '倩女幽魂-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1956', '光明大陆');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2064', '光明大陆-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1879', '光明大陆-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('15', '克鲁赛德战记');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1834', '全本小说书城');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2047', '全民斗妖传');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1939', '内涵超人');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1990', '凤凰新闻');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1897', '剑舞苍穹-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1961', '劲舞团');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2053', '劲舞团-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1910', '劲舞团-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1913', '劲舞团-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1996', '去哪儿旅行');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1862', '去哪儿旅行-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1984', '变啦');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('44', '口袋小军团');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('60', '口袋要塞');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('553', '可得眼镜');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1986', '咪咕视频');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1874', '咪咕视频-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1935', '嘀嗒出行');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1857', '嘀嗒拼车-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1836', '塔防魏蜀吴');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1', '大众点评');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2052', '大众点评-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1883', '大众点评-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1889', '大众点评-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2042', '大唐无双');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('30', '大掌门');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('56', '大话西游');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2070', '大话西游-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('46', '天使纪元');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1873', '天使纪元-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('33', '天命契约');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1959', '天生不凡');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1902', '天生不凡-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('23', '奇迹觉醒');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2009', '守望物语');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2067', '守望物语-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1898', '安居客-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('83', '宾果消消消');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2004', '封印猎人');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2051', '封印猎人-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1940', '封神战纪');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('38', '封神问情');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2028', '小猪短租');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2032', '少年三国志');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2041', '山海异闻录');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1868', '山海经-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1907', '山海经-MM');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1882', '山海经-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2012', '山海经-QQ');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1841', '帮帮测');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1937', '当当网');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('29', '征途2');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2024', '御灵醉月');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1829', '微视');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1875', '微视-W');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1960', '心动劲舞团');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1905', '心动劲舞团-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1957', '忍者一刀');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1871', '忍者一刀-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('59', '快手');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1864', '快手-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1970', '我叫MT世界');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('19', '我是大官人');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1964', '我的王朝');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2071', '我的王朝-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1918', '我的王朝-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1833', '我的野蛮总裁');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('52', '战国志');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2058', '战国志-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1900', '战国志-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2031', '扶摇仙灵');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1980', '拍拍贷借款');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('11', '择天记');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('55', '拳皇命运-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1846', '拳皇命运-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('126', '拼多多-H');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('7', '拼多多-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1923', '拼多多-MM');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('9', '拼多多-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2019', '拼多多-QForJXX');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1845', '拼多多-W');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1877', '拼多多-Whn');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1915', '拼多多-WW');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('51', '捕兽传');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1983', '携程旅行');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2025', '携程旅行-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2022', '摩天轮票务');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1912', '摩天轮票务-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1997', '收钱呗');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1886', '放置奇兵-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1954', '无双西湖');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1861', '无双西湖-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1975', '明月传说');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1840', '暗黑荣耀');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('17', '朕的后宫');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1947', '来伊份商城');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('40', '校花攻略');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('41', '梦幻西游');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2039', '梦幻西游-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1929', '梦想西域-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1958', '楚留香');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1884', '楚留香-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1892', '武林外传-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1967', '每日优鲜');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1921', '每日优鲜-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2010', '毛豆新车');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2026', '毛豆新车-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1942', '洋码头');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('10', '消除者联盟');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1891', '消除者联盟-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1895', '消除者联盟-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1835', '漫威超级争霸战');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1998', '澎湃新闻');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2000', '炎龙大陆');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1950', '炮轰三国');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('27', '烈火如歌');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2063', '烈火如歌-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1872', '烈火如歌-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1880', '烈火如歌-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2015', '烈火如歌-QQ');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1966', '熹妃Q传');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1858', '熹妃Q传-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('20', '爱奇艺');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2045', '爱奇艺-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1853', '爱奇艺-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1876', '爱奇艺-My');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1938', '爱彼迎');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('61', '猎人sss');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('32', '猎人学院');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('26', '猎魂觉醒');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1856', '瓜子二手车-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2011', '瓜子二手车-MM');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1952', '百合网');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2068', '百合网-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1899', '百合网-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2046', '百度外卖');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1953', '神武3');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1928', '神武3-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('28', '第五人格');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1978', '简书');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2020', '粉碎狂热');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1982', '红颜三国');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1949', '约单');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1989', '网易红彩');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2006', '网易红彩-0');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2061', '网易红彩-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2062', '网易红彩-2');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1922', '网易红彩-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1844', '网易考拉海购');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1943', '网易考拉海购-H');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('22', '美团');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1852', '美团-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2016', '美团-MForJXX');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1916', '美团-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1951', '脉脉');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2055', '脉脉-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1981', '腾讯FIFA足球世界');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2060', '腾讯FIFA足球世界-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1859', '腾讯FIFA足球世界-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1854', '腾讯_FIFA_ONLINE-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1976', '腾讯魔力宝贝');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1992', '至尊王爷');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1999', '芒果TV');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2043', '芒果TV-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1896', '花椒直播-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('16', '苍之纪元');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1919', '苍之纪元-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1920', '苍之纪元-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('50', '英语流利说');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2069', '英语流利说-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1948', '荔枝FM');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2002', '蓝月传承霸业');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2066', '蓝月传承霸业-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2001', '蓬莱仙域');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2', '蘑菇街');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1866', '蘑菇街-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2017', '蘑菇街-MForJXX');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1847', '虎牙直播-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1917', '虎牙直播-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2048', '蜀山奇侠传');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1945', '蜻蜓FM');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1979', '西游女儿国');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2054', '西游女儿国-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('18', '诛仙');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2037', '诛仙-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1941', '诸侯征战');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1991', '诺文尼亚');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2057', '诺文尼亚-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2013', '货拉拉');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2044', '车主无忧');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('12', '轮回诀');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2036', '轮回诀-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('48', '远古世界');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1838', '逆仙纪');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('39', '都市英豪');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1855', '酷狗直播-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1925', '酷狗直播-MM');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2049', '醒购');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1962', '金牌投资人');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2065', '金牌投资人-1');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1930', '金牌投资人-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1974', '银河战舰');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2034', '镇魔曲');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1848', '闪电降价-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1963', '闪送');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1924', '闪送-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1988', '阿里巴巴1688');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2014', '非人学园');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1894', '食之契约-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1904', '食之契约-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('3', '饿了么');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1909', '饿了么-W');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1971', '饿了么-WW');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1973', '饿了么-WWW');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('14', '高德地图');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1932', '高德地图-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1934', '高德地图-MM');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1911', '魔剑契约-M');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('1914', '魔剑契约-Q');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('34', '魔纹三国');
INSERT INTO `fx_advert` (`id`,`adname`) VALUES ('2029', '黑龙波挂机');
SET FOREIGN_KEY_CHECKS=1;
